import jsPDF from "jspdf"
import { createRoot } from "react-dom/client"
import { flushSync } from "react-dom"
import { StaticFrame } from "@/components/playbook/editor"
import { SCALE, courtLength } from "@/lib/playbook/geometry"
import {
  COURT_WIDTH_M,
  type Play,
  type PlayAction,
  type PlayElement,
} from "@/lib/playbook/types"
import {
  BRAND,
  BRAND_DARK,
  INK,
  BODY,
  SUBTLE,
  LINE,
  MARGIN,
  CONTENT_W,
  BOTTOM_LIMIT,
  setText,
  setDraw,
  topBand,
  addFooters,
  sectionHeading,
  ensure,
  renderAnalysis,
} from "@/lib/pdf/brand"

/**
 * Branded PDF report of a full play: cover data, personnel, every frame's
 * diagram with its note and actions, and the AI tactical analysis when one
 * has been generated. Shares the visual template with the trade reports.
 */

function getStrings(locale: string) {
  const isEn = locale === "en"
  return {
    reportTitle: isEn ? "Playbook — play report" : "Playbook — informe de jugada",
    courtLabel: isEn ? "Court" : "Pista",
    halfCourt: isEn ? "Half court" : "Media pista",
    fullCourt: isEn ? "Full court" : "Pista completa",
    framesLabel: isEn ? "frames" : "fotogramas",
    teamLabel: isEn ? "Designed for" : "Diseñada para",
    description: isEn ? "Play description" : "Descripción de la jugada",
    personnel: isEn ? "Personnel" : "Personal en pista",
    attackers: isEn ? "Attackers" : "Atacantes",
    defenders: isEn ? "Defenders" : "Defensores",
    extras: isEn ? "Also on court" : "También en pista",
    ballWord: isEn ? "ball" : "balón",
    coneWord: isEn ? "cone" : "cono",
    coachWord: isEn ? "coach" : "entrenador",
    sequence: isEn ? "Play sequence" : "Secuencia de la jugada",
    frameWord: isEn ? "Frame" : "Fotograma",
    noActions: isEn
      ? "No drawn actions — players relocate directly."
      : "Sin acciones dibujadas — los jugadores se recolocan directamente.",
    aiAnalysis: isEn ? "AI tactical analysis" : "Análisis táctico de IA",
    generatedBy: isEn
      ? "Generated by Global Hoop Stats · Playbook beta."
      : "Generado por Global Hoop Stats · Playbook beta.",
    dateLocale: isEn ? "en-US" : "es-ES",
  }
}

function elName(el: PlayElement | undefined, s: ReturnType<typeof getStrings>): string {
  if (!el) return "?"
  if (el.kind === "attacker") {
    return el.player ? `O${el.label} (${el.player.name})` : `O${el.label}`
  }
  if (el.kind === "defender") return `X${el.label}`
  if (el.kind === "ball") return s.ballWord
  if (el.kind === "coach") return s.coachWord
  return `${s.coneWord} ${el.label}`.trim()
}

function actionText(
  play: Play,
  action: PlayAction,
  locale: string,
  s: ReturnType<typeof getStrings>,
): string {
  const isEn = locale === "en"
  const actor = elName(play.elements.find((e) => e.id === action.elementId), s)
  const target = action.targetElementId
    ? elName(play.elements.find((e) => e.id === action.targetElementId), s)
    : null
  switch (action.type) {
    case "pass":
      return isEn ? `${actor} passes to ${target ?? "?"}` : `${actor} pasa a ${target ?? "?"}`
    case "handoff":
      return isEn ? `${actor} hands off to ${target ?? "?"}` : `${actor} mano a mano con ${target ?? "?"}`
    case "screen":
      return target
        ? isEn
          ? `${actor} screens for ${target}`
          : `${actor} bloquea para ${target}`
        : isEn
          ? `${actor} sets a screen`
          : `${actor} pone un bloqueo`
    case "dribble":
      return isEn ? `${actor} attacks off the dribble` : `${actor} ataca con bote`
    case "cut":
      return isEn ? `${actor} cuts` : `${actor} corta`
  }
}

/** Rasterize one frame's diagram to a PNG data URL (white background). */
async function frameToPng(play: Play, frameIdx: number): Promise<string> {
  const host = document.createElement("div")
  const root = createRoot(host)
  flushSync(() => root.render(<StaticFrame play={play} frameIdx={frameIdx} />))
  const markup = host.innerHTML
  root.unmount()

  const w = COURT_WIDTH_M * SCALE
  const h = courtLength(play.courtType) * SCALE
  const blob = new Blob([markup], { type: "image/svg+xml;charset=utf-8" })
  const url = URL.createObjectURL(blob)
  try {
    const img = await new Promise<HTMLImageElement>((resolve, reject) => {
      const el = new Image()
      el.onload = () => resolve(el)
      el.onerror = () => reject(new Error("Could not rasterize frame"))
      el.src = url
    })
    const pxScale = 2
    const canvas = document.createElement("canvas")
    canvas.width = w * pxScale
    canvas.height = h * pxScale
    const ctx = canvas.getContext("2d")
    if (!ctx) throw new Error("Canvas unavailable")
    ctx.fillStyle = "#ffffff"
    ctx.fillRect(0, 0, canvas.width, canvas.height)
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height)
    return canvas.toDataURL("image/png")
  } finally {
    URL.revokeObjectURL(url)
  }
}

export async function exportPlayPdf({
  play,
  analysis,
  locale = "es",
}: {
  play: Play
  /** Current AI analysis of this play, included when present. */
  analysis?: string | null
  locale?: string
}): Promise<void> {
  const s = getStrings(locale)
  const doc = new jsPDF({ unit: "mm", format: "a4" })

  topBand(doc, s.reportTitle, s.dateLocale)

  // ── Cover data ─────────────────────────────────────────────────────────
  let y = 32
  doc.setFont("helvetica", "bold")
  doc.setFontSize(17)
  setText(doc, INK)
  doc.text(play.name, MARGIN, y)
  y += 6.5

  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  setText(doc, SUBTLE)
  const metaParts = [
    `${s.courtLabel}: ${play.courtType === "half" ? s.halfCourt : s.fullCourt}`,
    `${play.frames.length} ${s.framesLabel}`,
  ]
  if (play.team) {
    metaParts.push(`${s.teamLabel}: ${play.team.name} (${play.team.leagueSlug.toUpperCase()})`)
  }
  doc.text(metaParts.join("   ·   "), MARGIN, y)
  y += 9

  // ── Description ────────────────────────────────────────────────────────
  if (play.description) {
    y = ensure(doc, y, 18)
    y = sectionHeading(doc, s.description, y)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9.5)
    setText(doc, BODY)
    for (const ln of doc.splitTextToSize(play.description, CONTENT_W) as string[]) {
      y = ensure(doc, y, 6)
      doc.text(ln, MARGIN, y)
      y += 4.6
    }
    y += 4
  }

  // ── Personnel ──────────────────────────────────────────────────────────
  const attackers = play.elements.filter((e) => e.kind === "attacker")
  const defenders = play.elements.filter((e) => e.kind === "defender")
  const extras = play.elements.filter(
    (e) => e.kind === "ball" || e.kind === "cone" || e.kind === "coach",
  )
  y = ensure(doc, y, 20)
  y = sectionHeading(doc, s.personnel, y)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  if (attackers.length > 0) {
    setText(doc, BODY)
    const names = attackers
      .map((a) => (a.player ? `O${a.label} — ${a.player.name}${a.player.position ? ` (${a.player.position})` : ""}` : `O${a.label}`))
      .join("   ·   ")
    for (const ln of doc.splitTextToSize(`${s.attackers}: ${names}`, CONTENT_W) as string[]) {
      y = ensure(doc, y, 6)
      doc.text(ln, MARGIN, y)
      y += 4.6
    }
  }
  if (defenders.length > 0) {
    y = ensure(doc, y, 6)
    setText(doc, BODY)
    doc.text(`${s.defenders}: ${defenders.map((d) => `X${d.label}`).join(", ")}`, MARGIN, y)
    y += 4.6
  }
  if (extras.length > 0) {
    y = ensure(doc, y, 6)
    setText(doc, SUBTLE)
    const words = extras.map((e) =>
      e.kind === "ball" ? s.ballWord : e.kind === "coach" ? s.coachWord : `${s.coneWord} ${e.label}`.trim(),
    )
    doc.text(`${s.extras}: ${words.join(", ")}`, MARGIN, y)
    y += 4.6
  }
  y += 4

  // ── Frames: diagram left, note + actions right ─────────────────────────
  y = ensure(doc, y, 16)
  y = sectionHeading(doc, s.sequence, y)

  const imgW = play.courtType === "half" ? 88 : 52
  const imgH = imgW * (courtLength(play.courtType) / COURT_WIDTH_M)
  const textX = MARGIN + imgW + 7
  const textW = CONTENT_W - imgW - 7

  for (let i = 0; i < play.frames.length; i++) {
    const frame = play.frames[i]
    const png = await frameToPng(play, i)

    y = ensure(doc, y, Math.min(imgH + 10, BOTTOM_LIMIT - 20))
    const top = y

    setDraw(doc, LINE)
    doc.setLineWidth(0.2)
    doc.addImage(png, "PNG", MARGIN, top, imgW, imgH)
    doc.rect(MARGIN, top, imgW, imgH)

    let ty = top + 4.5
    doc.setFont("helvetica", "bold")
    doc.setFontSize(11)
    setText(doc, BRAND_DARK)
    doc.text(`${s.frameWord} ${i + 1} / ${play.frames.length}`, textX, ty)
    ty += 5.5

    if (frame.note) {
      doc.setFont("helvetica", "italic")
      doc.setFontSize(9)
      setText(doc, INK)
      for (const ln of doc.splitTextToSize(frame.note, textW) as string[]) {
        if (ty > top + imgH - 2) break
        doc.text(ln, textX, ty)
        ty += 4.4
      }
      ty += 1.5
    }

    doc.setFont("helvetica", "normal")
    doc.setFontSize(8.5)
    if (frame.actions.length > 0) {
      for (const a of frame.actions) {
        const line = actionText(play, a, locale, s)
        for (const ln of doc.splitTextToSize(line, textW - 4) as string[]) {
          if (ty > top + imgH - 2) break
          setText(doc, BRAND)
          doc.text("•", textX, ty)
          setText(doc, BODY)
          doc.text(ln, textX + 3.5, ty)
          ty += 4.2
        }
      }
    } else if (i < play.frames.length - 1) {
      setText(doc, SUBTLE)
      doc.text(s.noActions, textX, ty)
    }

    y = top + imgH + 7
  }

  // ── AI analysis ────────────────────────────────────────────────────────
  if (analysis) {
    y = ensure(doc, y, 20)
    y = sectionHeading(doc, s.aiAnalysis, y)
    renderAnalysis(doc, analysis, y)
  }

  addFooters(doc, s.generatedBy)
  doc.save(`${slugifyName(play.name)}.pdf`)
}

function slugifyName(name: string): string {
  return (
    name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "jugada"
  )
}
