import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import { formatEur } from "@/lib/market/league-strength"
import type { Valuation } from "@/lib/market/valuation"

type ReportPlayer = {
  name: string
  position: string | null
  team: string | null
  league: string | null
  valuation: Valuation | null
}

type SimularData = {
  mode: "Simular"
  outgoing: ReportPlayer
  scenarios: {
    verdict: string
    balance: number
    combinedValueEur: number
    incoming: ReportPlayer[]
  }[]
  /** scenario index → AI analysis text */
  analyses?: Record<number, string>
}

type ProponerData = {
  mode: "Proponer"
  outgoing: ReportPlayer[]
  incoming: ReportPlayer[]
  cash: number
  terms: string
  balance: number
  analysis?: string | null
}

// ── Locale-aware strings ───────────────────────────────────────────
function getStrings(locale: string) {
  const isEn = locale === "en"
  return {
    reportTitleSim: isEn ? "Trade simulation report" : "Informe de simulación de traspaso",
    reportTitleProp: isEn ? "Trade proposal report" : "Informe de propuesta de traspaso",
    playerToTrade: isEn ? "Player to trade" : "Jugador a traspasar",
    scenariosFound: isEn ? "Scenarios found" : "Escenarios encontrados",
    detailAndAnalysis: isEn ? "Detail and analysis of each proposal" : "Detalle y análisis de cada propuesta",
    aiAnalysis: isEn ? "AI ANALYSIS OF THIS TRADE" : "ANÁLISIS DE IA DE ESTE TRASPASO",
    propTitle: isEn ? "Custom trade proposal" : "Propuesta de traspaso personalizada",
    youGive: isEn ? "Players you give" : "Jugadores que entregas",
    youReceive: isEn ? "Players you receive" : "Jugadores que recibes",
    valueGiven: isEn ? "Value given" : "Valor entregado",
    valueReceived: isEn ? "Value received" : "Valor recibido",
    balance: isEn ? "Balance" : "Balance",
    verdict: isEn ? "Verdict" : "Veredicto",
    balanced: isEn ? "Balanced proposal" : "Propuesta equilibrada",
    giveMore: isEn ? "You give more value than you receive" : "Entregas más valor del que recibes",
    receiveMore: isEn ? "You receive more value than you give" : "Recibes más valor del que entregas",
    additionalTerms: isEn ? "Additional terms" : "Términos adicionales",
    aiProposal: isEn ? "AI analysis of the proposal" : "Análisis de IA de la propuesta",
    estimatedValue: isEn ? "Estimated value" : "Valor estimado",
    annualSalary: isEn ? "Annual salary" : "Salario anual",
    rating: isEn ? "Rating" : "Puntuación",
    includesCash: isEn ? "includes" : "incluye",
    inCash: isEn ? "in cash" : "en efectivo",
    generatedBy: isEn
      ? "Generated by Global Hoop Stats · Figures are heuristic estimates, not actual contract values."
      : "Generado por Global Hoop Stats · Las cifras son estimaciones heurísticas, no valores contractuales reales.",
    tableHeaders: isEn
      ? ["#", "Players received", "Qty", "Total value", "Balance", "Verdict"]
      : ["#", "Jugadores recibidos", "Cant.", "Valor total", "Balance", "Veredicto"],
    proposalLabel: isEn ? "Proposal" : "Propuesta",
    balanceLabel: isEn ? "balance" : "balance",
    dateLocale: isEn ? "en-US" : "es-ES",
  }
}

// ── Palette (light, print-friendly, brand-accented) ──────────────
type RGB = [number, number, number]
const BRAND: RGB = [230, 106, 30]
const BRAND_DARK: RGB = [183, 78, 14]
const INK: RGB = [26, 24, 22]
const BODY: RGB = [62, 60, 64]
const SUBTLE: RGB = [122, 120, 126]
const LIGHTFILL: RGB = [245, 244, 246]
const LINE: RGB = [223, 221, 226]

const PAGE_W = 210
const MARGIN = 16
const CONTENT_W = PAGE_W - MARGIN * 2
const BOTTOM_LIMIT = 274

const setText = (doc: jsPDF, c: RGB) => doc.setTextColor(c[0], c[1], c[2])
const setFill = (doc: jsPDF, c: RGB) => doc.setFillColor(c[0], c[1], c[2])
const setDraw = (doc: jsPDF, c: RGB) => doc.setDrawColor(c[0], c[1], c[2])

/** Vector approximation of the GH basketball mark. */
function drawLogo(doc: jsPDF, cx: number, cy: number, r: number) {
  setFill(doc, [255, 255, 255])
  doc.circle(cx, cy, r, "F")
  setDraw(doc, BRAND_DARK)
  doc.setLineWidth(0.3)
  doc.line(cx - r, cy, cx + r, cy)
  doc.line(cx, cy - r, cx, cy + r)
  setText(doc, BRAND_DARK)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(r * 1.45)
  doc.text("GH", cx, cy + r * 0.5, { align: "center" })
}

function topBand(doc: jsPDF, subtitle: string, locale: string) {
  const s = getStrings(locale)
  setFill(doc, BRAND)
  doc.rect(0, 0, PAGE_W, 22, "F")
  drawLogo(doc, MARGIN + 5, 11, 5.5)
  setText(doc, [255, 255, 255])
  doc.setFont("helvetica", "bold")
  doc.setFontSize(13)
  doc.text("GLOBAL HOOP STATS", MARGIN + 14, 10)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(8.5)
  doc.text(subtitle, MARGIN + 14, 15.5)
  doc.setFontSize(8)
  doc.text(
    new Date().toLocaleDateString(s.dateLocale, {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    PAGE_W - MARGIN,
    13,
    { align: "right" },
  )
}

function addFooters(doc: jsPDF, locale: string) {
  const s = getStrings(locale)
  const total = doc.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    setDraw(doc, LINE)
    doc.setLineWidth(0.2)
    doc.line(MARGIN, 285, PAGE_W - MARGIN, 285)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(7)
    setText(doc, SUBTLE)
    doc.text(s.generatedBy, MARGIN, 290)
    doc.text(`${i} / ${total}`, PAGE_W - MARGIN, 290, { align: "right" })
  }
}

function sectionHeading(doc: jsPDF, text: string, y: number): number {
  setFill(doc, BRAND)
  doc.rect(MARGIN, y - 3.4, 1.6, 4.6, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(12)
  setText(doc, INK)
  doc.text(text, MARGIN + 4.5, y)
  return y + 6.5
}

function ensure(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > BOTTOM_LIMIT) {
    doc.addPage()
    return 20
  }
  return y
}

/** Render an AI analysis (light markdown) at y, returns new y. */
function renderAnalysis(doc: jsPDF, text: string, y: number): number {
  for (const raw of text.split("\n")) {
    const line = raw.trim()
    if (!line) {
      y += 1.8
      continue
    }
    let content = line
    let bullet = false
    let heading = false
    if (content.startsWith("### ")) {
      content = content.slice(4)
      heading = true
    } else if (content.startsWith("## ")) {
      content = content.slice(3)
      heading = true
    } else if (content.startsWith("- ") || content.startsWith("* ")) {
      content = content.slice(2)
      bullet = true
    }
    content = content.replace(/\*\*/g, "").trim()
    if (!content) continue
    doc.setFont("helvetica", heading ? "bold" : "normal")
    doc.setFontSize(heading ? 10 : 9)
    const indent = bullet ? MARGIN + 5 : MARGIN
    const wrapW = bullet ? CONTENT_W - 5 : CONTENT_W
    const wrapped = doc.splitTextToSize(content, wrapW) as string[]
    for (let i = 0; i < wrapped.length; i++) {
      y = ensure(doc, y, 6)
      if (bullet && i === 0) {
        setText(doc, BRAND)
        doc.text("•", MARGIN + 1.5, y)
      }
      setText(doc, heading ? INK : BODY)
      doc.text(wrapped[i], indent, y)
      y += heading ? 5 : 4.5
    }
    if (heading) y += 1
  }
  return y
}

export function exportTradePdf(data: SimularData | ProponerData, locale = "en") {
  const s = getStrings(locale)
  const doc = new jsPDF({ unit: "mm", format: "a4" })

  topBand(
    doc,
    data.mode === "Simular" ? s.reportTitleSim : s.reportTitleProp,
    locale,
  )

  // Title line
  let y = 32
  doc.setFont("helvetica", "bold")
  doc.setFontSize(17)
  setText(doc, INK)
  const title =
    data.mode === "Simular"
      ? data.outgoing.name
      : s.propTitle
  doc.text(title, MARGIN, y)
  y += 9

  if (data.mode === "Simular") {
    renderSimular(doc, data, y, locale)
  } else {
    renderProponer(doc, data, y, locale)
  }

  addFooters(doc, locale)
  doc.save(`traspaso-${data.mode.toLowerCase()}-${Date.now()}.pdf`)
}

function playerLine(p: ReportPlayer): string {
  return `${p.name} · ${p.position ?? "—"} · ${p.team ?? "FA"} · ${p.league ?? "—"}`
}

function renderSimular(doc: jsPDF, data: SimularData, startY: number, locale: string) {
  const s = getStrings(locale)
  let y = startY

  // Outgoing player card
  y = sectionHeading(doc, s.playerToTrade, y)
  setFill(doc, LIGHTFILL)
  setDraw(doc, LINE)
  doc.setLineWidth(0.2)
  const cardH = data.outgoing.valuation ? 24 : 12
  doc.roundedRect(MARGIN, y - 2, CONTENT_W, cardH, 1.6, 1.6, "FD")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  setText(doc, INK)
  doc.text(data.outgoing.name, MARGIN + 4, y + 4)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  setText(doc, SUBTLE)
  doc.text(
    `${data.outgoing.position ?? "—"} · ${data.outgoing.team ?? "FA"} · ${data.outgoing.league ?? "—"}`,
    MARGIN + 4,
    y + 9,
  )
  if (data.outgoing.valuation) {
    setText(doc, BODY)
    doc.text(
      `${s.estimatedValue}: ${formatEur(data.outgoing.valuation.eur)}   ·   ${s.annualSalary}: ${formatEur(data.outgoing.valuation.annualEur)}   ·   ${s.rating}: ${data.outgoing.valuation.rating}/100 (${data.outgoing.valuation.tier})`,
      MARGIN + 4,
      y + 16,
    )
  }
  y += cardH + 6

  // Scenarios summary table
  y = ensure(doc, y, 24)
  y = sectionHeading(doc, s.scenariosFound, y)
  const rows = data.scenarios.map((sc, i) => [
    `#${i + 1}`,
    sc.incoming.map((p) => p.name).join(", "),
    String(sc.incoming.length),
    formatEur(sc.combinedValueEur),
    sc.balance.toFixed(2),
    sc.verdict,
  ])
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    tableWidth: CONTENT_W,
    theme: "grid",
    head: [s.tableHeaders],
    body: rows,
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 8 },
    bodyStyles: { textColor: INK, fontSize: 8 },
    alternateRowStyles: { fillColor: LIGHTFILL },
    styles: { lineColor: LINE, lineWidth: 0.1, cellPadding: 2.2 },
    columnStyles: { 0: { cellWidth: 12 }, 2: { cellWidth: 12 }, 4: { cellWidth: 18 } },
  })
   
  y = (doc as any).lastAutoTable.finalY + 9

  // Detailed scenarios + AI analyses
  y = ensure(doc, y, 16)
  y = sectionHeading(doc, s.detailAndAnalysis, y)

  data.scenarios.forEach((sc, i) => {
    y = ensure(doc, y, 20)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(10.5)
    setText(doc, BRAND_DARK)
    doc.text(`${s.proposalLabel} #${i + 1} — ${s.balanceLabel} ${sc.balance.toFixed(2)}`, MARGIN, y)
    y += 5
    doc.setFont("helvetica", "italic")
    doc.setFontSize(9)
    setText(doc, SUBTLE)
    const vWrapped = doc.splitTextToSize(sc.verdict, CONTENT_W) as string[]
    for (const ln of vWrapped) {
      y = ensure(doc, y, 6)
      doc.text(ln, MARGIN, y)
      y += 4.4
    }
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    for (const p of sc.incoming) {
      y = ensure(doc, y, 6)
      setText(doc, BODY)
      const val = p.valuation ? `  —  ${formatEur(p.valuation.eur)} (${p.valuation.rating}/100)` : ""
      doc.text(`• ${playerLine(p)}${val}`, MARGIN + 2, y)
      y += 4.6
    }

    const analysis = data.analyses?.[i]
    if (analysis) {
      y += 1.5
      y = ensure(doc, y, 14)
      setFill(doc, [252, 246, 240])
      setDraw(doc, BRAND)
      doc.setLineWidth(0.2)
      const boxTop = y - 3
      // Label
      doc.setFont("helvetica", "bold")
      doc.setFontSize(8.5)
      setText(doc, BRAND_DARK)
      doc.text(s.aiAnalysis, MARGIN + 3, y + 1.5)
      y += 6
      const analysisStart = y
      y = renderAnalysis(doc, analysis, y)
      // left accent bar spanning the analysis block
      setDraw(doc, BRAND)
      doc.setLineWidth(0.8)
      doc.line(MARGIN, boxTop, MARGIN, Math.min(y, BOTTOM_LIMIT))
      void analysisStart
    }
    y += 7
  })
}

function renderProponer(doc: jsPDF, data: ProponerData, startY: number, locale: string) {
  const s = getStrings(locale)
  let y = startY

  const list = (label: string, players: ReportPlayer[]) => {
    y = ensure(doc, y, 16)
    y = sectionHeading(doc, label, y)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    if (players.length === 0) {
      setText(doc, SUBTLE)
      doc.text("—", MARGIN + 2, y)
      y += 5
      return
    }
    for (const p of players) {
      y = ensure(doc, y, 6)
      setText(doc, BODY)
      const val = p.valuation ? `  —  ${formatEur(p.valuation.eur)}` : ""
      doc.text(`• ${playerLine(p)}${val}`, MARGIN + 2, y)
      y += 4.8
    }
    y += 3
  }

  list(s.youGive, data.outgoing)
  list(s.youReceive, data.incoming)

  // Summary box
  y = ensure(doc, y, 34)
  const outVal =
    data.outgoing.reduce((sum, p) => sum + (p.valuation?.eur ?? 0), 0) + Math.abs(data.cash)
  const inVal = data.incoming.reduce((sum, p) => sum + (p.valuation?.eur ?? 0), 0)
  let verdict = s.balanced
  if (data.balance < 0.95) verdict = s.giveMore
  else if (data.balance > 1.08) verdict = s.receiveMore

  setFill(doc, LIGHTFILL)
  setDraw(doc, LINE)
  doc.setLineWidth(0.2)
  doc.roundedRect(MARGIN, y, CONTENT_W, 30, 1.6, 1.6, "FD")
  y += 7
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  setText(doc, BODY)
  doc.text(`${s.valueGiven}: ${formatEur(outVal)}` + (data.cash ? `  (${s.includesCash} ${formatEur(Math.abs(data.cash))} ${s.inCash})` : ""), MARGIN + 6, y)
  y += 5.5
  doc.text(`${s.valueReceived}: ${formatEur(inVal)}`, MARGIN + 6, y)
  y += 5.5
  doc.text(`${s.balance}: ${data.balance.toFixed(2)}`, MARGIN + 6, y)
  y += 5.5
  doc.setFont("helvetica", "bold")
  setText(doc, BRAND_DARK)
  doc.text(`${s.verdict}: ${verdict}`, MARGIN + 6, y)
  y += 9

  if (data.terms) {
    y = ensure(doc, y, 14)
    y = sectionHeading(doc, s.additionalTerms, y)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(9)
    setText(doc, BODY)
    for (const ln of doc.splitTextToSize(data.terms, CONTENT_W) as string[]) {
      y = ensure(doc, y, 6)
      doc.text(ln, MARGIN, y)
      y += 4.5
    }
    y += 4
  }

  if (data.analysis) {
    y = ensure(doc, y, 16)
    y = sectionHeading(doc, s.aiProposal, y)
    y = renderAnalysis(doc, data.analysis, y)
  }
}
